site_name: Updated Classic documentation
site_url: https://updated-classic-docs.github.io/guide
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true
      reconfigure_material: true
      reconfigure_search: true

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - "index.md"
  - Grand Theft Auto 3:
    - "gta3/index.md"
    # - "gta3/demonstration.md"
    - "gta3/download.md"
    - "gta3/addons.md"    
    - "gta3/faq.md" 
    - "gta3/credits.md" 
  - Grand Theft Auto Vice City:
    - "gtavc/index.md"
    # - "gtavc/demonstration.md"    
    - "gtavc/download.md"    
    - "gtavc/addons.md"    
    - "gtavc/faq.md"    
    - "gtavc/credits.md"
  - Grand Theft Auto San Andreas:
    - "gtasa/index.md"        
    # - "gtasa/demonstration.md"        
    - "gtasa/download.md"        
    - "gtasa/addons.md"        
    - "gtasa/faq.md"        
    - "gtasa/credits.md"
  - Max Payne:
    - "mp1/index.md" 
    - "mp1/download.md"
  - Max Payne 2:
    - "mp2/index.md"   
    - "mp2/download.md"
  - Bully SE:
    - "bse/index.md"   
    - "bse/download.md"     
    - "bse/faq.md"
  - Midnight Club II:
    - "mc2/index.md"
    - "mc2/download.md"                
  # - Grand Theft Auto 3 [FULL TEXT]:
  #   - "gta3_eng.md"